spring:
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: root
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-expiration: 900000
  refresh-expiration: 604800000
